GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/info

###
GET http://localhost:3001/api/persons/6946cfc3380608b5561baf11

###
DELETE http://localhost:3001/api/persons/69568e6dd1b0f6b33ee00a4c

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "llian rose",
    "number": "040-175522"
}

###
PUT http://localhost:3001/api/persons/6946cf8ac220eea53e3a6ac7
Content-Type: application/json

{
    "name": "Reagan Smith",
    "number": "044-555666"
}

###
//tests for deployed backend
GET https://fullstackopen-part3-4n3j.onrender.com/api/persons

###
GET https://fullstackopen-part3-4n3j.onrender.com/api/info

###
GET https://fullstackopen-part3-4n3j.onrender.com/api/persons/69495c40e70bcb910bc46fae

###
DELETE https://fullstackopen-part3-4n3j.onrender.com/api/persons/7562

###
POST https://fullstackopen-part3-4n3j.onrender.com/api/persons
Content-Type: application/json

{
    "name": "Mikko Virtanen",
    "number": "044-555666"
}

###
PUT https://fullstackopen-part3-4n3j.onrender.com/api/persons/6946cf8ac220eea53e3a6ac7
Content-Type: application/json

{
    "name": "Reagan Smith",
    "number": "044-555666"
}